language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gabcodearmada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabcodearmada/docker-react npm run test